package persistencias;
// Generated 16 feb 2026, 15:28:35 by Hibernate Tools 5.4.33.Final

/**
 * VotosComunidadPartido generated by hbm2java
 */
public class VotosComunidadPartido implements java.io.Serializable {

	private VotosComunidadPartidoId id;
	private int votos19;
	private int votos1017;
	private int votos1825;
	private int votos2640;
	private int votos4165;
	private int votosMas66;
	private int totalVotos;

	public VotosComunidadPartido() {
	}

	public VotosComunidadPartido(VotosComunidadPartidoId id, int votos19, int votos1017, int votos1825, int votos2640,
			int votos4165, int votosMas66, int totalVotos) {
		this.id = id;
		this.votos19 = votos19;
		this.votos1017 = votos1017;
		this.votos1825 = votos1825;
		this.votos2640 = votos2640;
		this.votos4165 = votos4165;
		this.votosMas66 = votosMas66;
		this.totalVotos = totalVotos;
	}

	public VotosComunidadPartidoId getId() {
		return this.id;
	}

	public void setId(VotosComunidadPartidoId id) {
		this.id = id;
	}

	public int getVotos19() {
		return this.votos19;
	}

	public void setVotos19(int votos19) {
		this.votos19 = votos19;
	}

	public int getVotos1017() {
		return this.votos1017;
	}

	public void setVotos1017(int votos1017) {
		this.votos1017 = votos1017;
	}

	public int getVotos1825() {
		return this.votos1825;
	}

	public void setVotos1825(int votos1825) {
		this.votos1825 = votos1825;
	}

	public int getVotos2640() {
		return this.votos2640;
	}

	public void setVotos2640(int votos2640) {
		this.votos2640 = votos2640;
	}

	public int getVotos4165() {
		return this.votos4165;
	}

	public void setVotos4165(int votos4165) {
		this.votos4165 = votos4165;
	}

	public int getVotosMas66() {
		return this.votosMas66;
	}

	public void setVotosMas66(int votosMas66) {
		this.votosMas66 = votosMas66;
	}

	public int getTotalVotos() {
		return this.totalVotos;
	}

	public void setTotalVotos(int totalVotos) {
		this.totalVotos = totalVotos;
	}

}
