package persistencias;
// Generated 16 feb 2026, 15:28:35 by Hibernate Tools 5.4.33.Final

/**
 * VotosComunidadPartidoId generated by hbm2java
 */
public class VotosComunidadPartidoId implements java.io.Serializable {

	private String nombreComunidad;
	private String partidoPolitico;

	public VotosComunidadPartidoId() {
	}

	public VotosComunidadPartidoId(String nombreComunidad, String partidoPolitico) {
		this.nombreComunidad = nombreComunidad;
		this.partidoPolitico = partidoPolitico;
	}

	public String getNombreComunidad() {
		return this.nombreComunidad;
	}

	public void setNombreComunidad(String nombreComunidad) {
		this.nombreComunidad = nombreComunidad;
	}

	public String getPartidoPolitico() {
		return this.partidoPolitico;
	}

	public void setPartidoPolitico(String partidoPolitico) {
		this.partidoPolitico = partidoPolitico;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VotosComunidadPartidoId))
			return false;
		VotosComunidadPartidoId castOther = (VotosComunidadPartidoId) other;

		return ((this.getNombreComunidad() == castOther.getNombreComunidad())
				|| (this.getNombreComunidad() != null && castOther.getNombreComunidad() != null
						&& this.getNombreComunidad().equals(castOther.getNombreComunidad())))
				&& ((this.getPartidoPolitico() == castOther.getPartidoPolitico())
						|| (this.getPartidoPolitico() != null && castOther.getPartidoPolitico() != null
								&& this.getPartidoPolitico().equals(castOther.getPartidoPolitico())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNombreComunidad() == null ? 0 : this.getNombreComunidad().hashCode());
		result = 37 * result + (getPartidoPolitico() == null ? 0 : this.getPartidoPolitico().hashCode());
		return result;
	}

}
